models:
  gemma4_e4b:
    model: "gemma4:e4b"
    temperature: 0.8

  mistral_7b:
    model: "mistral:7b"
    temperature: 0.8
  
  qwen2.5_7b:
    model: "qwen2.5:7b"
    temperature: 0.8

  gemma4_e2b:
    model: "gemma4:e2b"
    temperature: 0.8

  deepseek_r1_14b:
    model: "deepseek-r1:14b"
    temperature:: 0.0

  response_model:
    model="gemma4:e4b",
    base_url="http://localhost:11434",
    reasoning=True,
    keep_alive=-1,
    temperature=1.0,
    top_p=0.95,
    top_k=64,
    num_ctx=8192,

  appraisal_model:
    model="gemma4:e4b",
    base_url="http://localhost:11434",
    reasoning=False,
    keep_alive=-1,
    num_ctx=8192